POST http://localhost:8080/api/forest/trees/classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1YW4uY3VldmFzZ0B1ZGVtLmVkdSIsImV4cCI6MTczMjY1OTg5MSwidXNlcmlkIjoxfQ.-eFuSzCiAMpTq5RBvw6LurTzgGR0D8yKVUy_hirK8t0

{
	"Names" : ["Backsjon", "Viken"]
}