POST http://localhost:8080/api/forest/overview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1YW4uY3VldmFzZ0B1ZGVtLmVkdSIsImV4cCI6MTczMjkzOTMwNCwidXNlcmlkIjoxfQ.Qah6Cd9eNAnQ-KE_qENG7UghvW1i6ed-h1sszYrnZ8U

{
	"Fid" : 3
}