GET http://localhost:8080/api/forests/map
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1YW4uY3VldmFzZ0B1ZGVtLmVkdSIsImV4cCI6MTczMjY2NzM3MCwidXNlcmlkIjoxfQ.TTtCi8q_2vjuUFog27DqZIIEXDG9DnJ0Euvps55Kl7M