POST http://localhost:8080/api/company
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1YW4uY3VldmFzZ0B1ZGVtLmVkdSIsImV4cCI6MTczMDU5MTgzOSwidXNlcmlkIjowfQ.dVQh4qvd2Mx6waIAvMweZcoWDJefVYBjJRtaUJTJ8-Q

{
	"name" : "UDEM"
}