POST http://localhost:8080/api/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1YW4uY3VldmFzZ0B1ZGVtLmVkdSIsImV4cCI6MTczMzA5NDIyNywidXNlcmlkIjoxfQ.LDd7wYLJHwjJFsc-aKfHRxhInyLKWCggAGRg6oKNmSM

{
	"name" : "Company 3"
}