POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "id": 1,
    "firstName": "juan",
    "lastName": "cuevas",
    "email": "juan.cuevasg@udem.edu",
    "password": "abc"
}
