POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "id": 2,
    "firstName": "juan2",
    "lastName": "cuevas2",
    "email": "juan.cuevasg@udem.edu2",
    "password": "abc"
}
